apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amortization-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.bradley-mader.com
      secretName: amortization-api-tls
  rules:
    - host: api.bradley-mader.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: amortization-api
                port:
                  number: 8080
